---
title: "Client Report - What's in a Name?"
subtitle: "Course DS 250"
author: "Ryan Lee"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


## Project Notes

__For Project 1 the answer to each question should include a chart **and** a written response. The years labels on your charts should not include a comma. At least **two** of your charts must include reference marks.__  

```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pd.read_csv("https://github.com/byuidatascience/data4names/raw/master/data-raw/names_year/names_year.csv")
```

```{python}
df.sort_values("name", ascending = False)
df.sort_values(["year", "Total"], ascending = False)
df.name.value_counts()
df.name.unique().shape[0]



```

## QUESTION|TASK 1

__How does your name at your birth year compare to its use historically?__

_type your results and analysis here_

```{python}
# name_ryan = ["Ryan"]
# df.query("name == 'Ryan' & year == 1997")

# year_ryan = [1997]
# df.query("year == 1997")

myName = df.query('name == "Ryan"')
(
  ggplot(data = myName,
  mapping = aes(x= 'year', y= 'Total')) +
  geom_line() +
  geom_rect(xmin = 1996, xmax = 1998, ymin = 1, ymax = 20000, fill = "red", alpha = .2, color = "rgba(0,0,0,0)")
)

```


## QUESTION|TASK 2

__If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?__

_type your results and analysis here_

```{python}
# Include and execute your code here
soBrittany = df.query('name == "Brittany"')
(
  ggplot (data = soBrittany,
  mapping = aes(x= 'year', y= 'Total')) +
  geom_point() +
  geom_rect(xmin = 1989, xmax = 1991, ymin = 31500, ymax = 34000, fill = "red", alpha = .2, color = "rgba(0,0,0,0)")
)

```


## QUESTION|TASK 3

__Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names in a single chart. What trends do you notice?__

_type your results and analysis here_

```{python}
# Include and execute your code here
fourNames = df.query('name == ["Mary", "Martha", "Peter", "Paul"]')
(
  ggplot (data = fourNames,
  mapping = aes(x= 'year', y= 'Total', color = 'name')) +
  geom_line() +
  labs(title = "Pattern") +
  scale_x_continuous(limits = [1920, 2000])
)        


```



## QUESTION|TASK 4

__Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?__  

_Nightmare on Elm Street has a huge impact in the horror culture. After the first film that was made _

```{python}
# Include and execute your code here
scarryMovie = df.query('name == "Freddy"')
(
  ggplot (data = scarryMovie,
  mapping = aes(x= 'year', y= 'Total')) +
  geom_point() +
  geom_rect(xmin = 1983, xmax = 1985, ymin = 100, ymax = 1000, fill = "red", alpha = .2, color = "rgba(0,0,0,0)")

)

```

---

## STRETCH QUESTION|TASK 1

__Reproduce the chart Elliot using the data from the `names_year.csv` file.__ 

_type your results and analysis here_

```{python}
# Include and execute your code here
isElliot = df.query('name == "Elliot"')
(
  ggplot(data = isElliot,
  mapping = aes(x= 'year', y= 'Total', color= "name")) +
  geom_line() +
  scale_color_manual(values={"Elliot": "blue"}) +
  scale_x_continuous(limits = [1950, 2020]) +
  geom_vline(xintercept = 1982, color = "red", linetype = 2) +
  geom_vline(xintercept = 1985, color = "red", linetype = 2) +
  geom_vline(xintercept = 2001, color = "red", linetype = 2)
)

```


---
